language: ruby

rvm:
  - 2.2.0

script:
  - RAILS_ENV=test rake db:create
  - RAILS_ENV=test rake db:migrate
  - RAILS_ENV=test bundle exec rspec

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/facebook.yml.dist config/facebook.yml

notifications:
  email: false

addons:
  code_climate:
    repo_token: d4ddfda51e7d49611ae2768ef2989b5f97645fb427c53e2d2ca14c4f55d53021
