version: "2"

services:
  web:
    build:
      dockerfile: docker/ruby/Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/warmapp-api
    environment:
      - RAILS_ENV=development
      - WARMAPP_DATABASE_HOST=postgres
      - WARMAPP_REDIS_HOST=redis
    ports:
      - "3000:3000"
    command: bin/rails server --binding=0.0.0.0 --port=3000

  test:
    build:
      dockerfile: docker/ruby/Dockerfile
      context: .
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/warmapp-api
    environment:
      - RAILS_ENV=test
      - WARMAPP_DATABASE_HOST=postgres
      - WARMAPP_REDIS_HOST=redis
    command: bin/bundle exec rspec

  postgres:
    image: postgres

  redis:
    image: redis

