rspec:
  build: .
  volumes:
    - .:/app
  environment:
    RAILS_ENV: test
  links:
    - postgres:postgres
  command: bundle exec rspec

postgres:
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
