web:
  build: .
  expose:
    - "8080:8080"
  volumes:
    - .:/app
  links:
    - postgres:postgres
  command: bundle exec unicorn -p 8080 -c ./config/unicorn.rb

nginx:
  build: ./docker/nginx/
  ports:
    - "80:80"
  links:
    - web:web

postgres:
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
